### ISSUE TITLE
当过早点击播放按钮时，播放器变为播放模式，但事实上没有开始播放

### ISSUE THREAD

**Issue by wu-yu-xuan** [132yse/eplayer#21]
![image](https://user-images.githubusercontent.com/35450080/80915874-8e8e1900-8d87-11ea-8014-9f9b3ccab85f.png)

**Comment by singlefor** [comment]
踩踩

**Comment by yisar** [comment]
我修一下试试……

**Comment by yisar** [comment]
好像修复了？
