### ISSUE TITLE
播放器的问题

### ISSUE THREAD

**Issue by j3812549** [132yse/eplayer#3]
点播放器暂停后，音量会恢复成默认值
点到播放器上，会从当前进度直接跳到初始进度

**Comment by j3812549** [comment]
调节声音的那一部分，可按的区域太小了，加点padding

**Comment by yisar** [comment]
以上，已修复，以下，请跟着提交::>_<::

**Comment by yisar** [comment]
好吧，我觉得还是关了吧……下次bug再开
