### ISSUE TITLE
对eplayer的一点建议

### ISSUE THREAD

**Issue by hunshikan** [132yse/eplayer#5]
1：兼容性问题是一个成熟产品必须要考虑的问题，希望作者慎重考虑
2：对移动端友好
3：增加点击播放画面，暂停功能
4：增加键盘可以方向键控制音量
5：增加弹幕功能

**Comment by yisar** [comment]
1. 目前通过 polyfill 兼容到 ie 11
2. 目前兼容所有移动端浏览器（因为替换为默认了）
3. 这个明天搞
4. 同样明天搞
5. 已发布弹幕库

**Comment by yisar** [comment]
3 已经搞定
全屏黑屏的问题也修复啦

4 下个版本搞，现在还没想到怎么跳出信息会比较有逼格::>_<::

**Comment by hunshikan** [comment]
高效啊，兄弟

**Comment by hunshikan** [comment]
不应该点击暂停，双击全屏吗<o.o>

**Comment by yisar** [comment]
可以的，明天搞定哈

**Comment by yisar** [comment]
双击点击全屏，搞定啦
